### ISSUE TITLE
Search via youtube-dl appears to be broken

### ISSUE THREAD

**Issue by Hartebee5t** [vicwomg/pikaraoke#54] opened 2020-10-23 23:45 UTC
Search of content not previously stored has stopped working and updating youtube-dl isn't fixing it.
A bit of digging reveals that the hosting repository at yt-dl.org is currently pointing to a GitHub DMCA take-down notice.

**Comment by vicwomg** [comment] 2020-10-23 23:53
It looks like YouTube broke the search functions. I think we'll just have to wait for YouTube-dl to fix it, but yes I heard the news about GitHub taking down YouTube-dl. That's a bit concerning and adds uncertainty to being able to fix this... but if it's limited to GitHub the project may live on.

**Comment by vicwomg** [comment] 2020-10-27 16:43
Full debug output of this error:

`
2020-10-27 09:42:14] INFO: Searching YouTube for: test karaoke
[2020-10-27 09:42:14] DEBUG: Youtube-dl search command: /usr/local/bin/youtube-dl -j --no-playlist --flat-playlist ytsearch10:"test karaoke"
ERROR: query ""test karaoke"": Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[2020-10-27 09:42:16] DEBUG: Error while executing search: Command '['/usr/local/bin/youtube-dl', '-j', '--no-playlist', '--flat-playlist', 'ytsearch10:"test karaoke"']' returned non-zero exit status 1.
[2020-10-27 09:42:16] ERROR: Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 183, in search
    search_results = k.get_karaoke_search_results(search_string)
  File "/Users/vicwong/coding/pikaraoke/karaoke.py", line 395, in get_karaoke_search_results
    return self.get_search_results(songTitle + " karaoke")
  File "/Users/vicwong/coding/pikaraoke/karaoke.py", line 392, in get_search_results
    raise e
  File "/Users/vicwong/coding/pikaraoke/karaoke.py", line 379, in get_search_results
    output = subprocess.check_output(cmd).decode("utf-8")
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/youtube-dl', '-j', '--no-playlist', '--flat-playlist', 'ytsearch10:"test karaoke"']' returned non-zero exit status 1.
`

**Comment by EdFabre** [comment] 2020-10-27 18:30
> Looks like the download function of YouTube-dl still works, so it's just search that's broken. If it starts to look like this won't be fixed for a while, I may have to resurrect the old way of searching using YouTube-scrape https://github.com/HermanFassett/youtube-scrape

Glad to see this project is active. I suspect youtube-dl will continue to release fixes via a private repo anyways. For the time being YouTube-scape seems the way to go. How fast this happens, if it happens depends on how modular the source code is.

**Comment by vicwomg** [comment] 2020-10-27 19:02
Note to self, here's the diff for when I added YouTube-scrape:
https://github.com/vicwomg/pikaraoke/commit/684024b2be4acca0b66ac71df697e619f6be7884

The big issue with YouTube-scrape is the need to host it somewhere, not super crazy about paying for hosting for this

**Comment by pablocamana** [comment] 2020-10-28 16:53
So if I understand this right, its just the search that's down. Beyond YouTube-scrape, would a potential workaround be to allow users to put directly into the search straight youtube links for the songs to add to que? That way you can still use the other features of the system, but you'd need to use a separate tab to search youtube?

**Comment by vicwomg** [comment] 2020-10-28 17:50
Yes it's just search that's broken in YouTube-dl

I can implement searching using YouTube-scrape (this is how it was done for a short while), and it should be seamless on the Pikaraoke side. The preference is always to use YouTube-dl so that there's less dependencies and we don't need to run a dedicated server just for executing the searching. So my hope is they simply fix it soon. If not, I'll look into using YouTube-scrape again, but perhaps it would be a fallback state or command line option.

**Comment by EdFabre** [comment] 2020-10-28 20:53
@vicwomg It is unclear how long youtube-dl will take due to the whole DMCA thing. Perhaps this failback state can allow users to point to their own heroku app to save on overall costs?

Also, the suggestion by @pablocamana could be an easier fix, and potentially a permanent feature in case normal search doesn't pull right vid.

**Comment by Hartebee5t** [comment] 2020-11-01 01:42
Great work @EdFabre !
I tried out your [pull request](https://github.com/vicwomg/pikaraoke/pull/57) and it worked a treat for restoring the search facility. 

I've yet to get the 'raw' search modifier to work, and the URL option converts everything to lower-case (which breaks yt ids), but I'm happy to be able to search again. Maybe I'm misinterpreting the new options' intentions.

**Comment by EdFabre** [comment] 2020-11-01 23:21
@Hartebee5t I just heard youtube-dl just  released a new update. My fix may be unnecessary 🙃. I will take a look at the search and url toLowerCase aspect of that field.

**Comment by vicwomg** [comment] 2020-11-02 00:39
Youtube-dl's latest update fixes it. This is the preferred solution

Update from the web interface, run 
"youtube-dl --update", or reinstall

**Comment by vicwomg** [comment] 2020-11-02 17:41
Closing.

In the future if there is a need to replace the search capability, I'd prefer to keep it python. There is a python library that scrapes YouTube search that I had not seen before:

https://github.com/alexmercerind/youtube-search-python

**Closed by vicwomg** 2020-11-02 17:41 UTC
Labels: bug
