### ISSUE TITLE
help with changing to sharednstorage location

### ISSUE THREAD

**Issue by Rwestrem** [vicwomg/pikaraoke#23] opened 2020-07-16 22:42 UTC
i have pikaraoke all set up and working great with the default settings.  I would like to save to my shared drive on another PC but im doing something wrong.  I have pikaraoke set up in rc.local so it auto starts.  My shared drive is   \\DESKTOP-MKD79SO\Shared Drive\pi\karaoke.   I have it setup like this...but its not downloading to the shared drive and im not sure where its going but it is downloading on the pi somewhere.  Is this right?

/usr/bin/python /home/pi/pikaraoke/app.py -d "\\DESKTOP-MKD79SO\Shared Drive\pi\karaoke" &

exit 0

**Comment by vicwomg** [comment] 2020-07-16 23:46
I haven't tried this sort of configuration. How is that shared drive mounted? nfs, samba?

As it is written I don't think it will work. Pikaraoke needs to be a unix path that can be written to. Also, that path has a space in it, which might be problematic, even if the path is quoted. 

From the command line, can you do this?

```
cd "\DESKTOP-MKD79SO\Shared Drive\pi\karaoke"
ls
touch test_file
```

**ls** should show the contents of the shared drive. **touch test_file** should put a blank file in it. If those things don't work, then pikaraoke wont be able to access the drive.

You may need to mount it as a writeable volume under /mnt how you do this depends on what kind of share it is. It _looks_ like SMB / windows, so maybe this:
https://raspberrypi.stackexchange.com/questions/40974/access-network-samba-share-from-pi-client

**Comment by Rwestrem** [comment] 2020-07-17 21:00
Yeah I guess the way I was trying wouldn't work like that.  I went ahead and mounted the drive and set it up in fstab.  That's where the next issue arises.  Fstab is trying to connect the shared drive before the network is up.  I created a cronjob to run sudo mount -a every 5 minutes which fixed that issue kinda.  So here is where I'm at now. I want pikaraoke to auto start and it.  I request a song to download and it downloads it to my network drive just fine but now it won't play anything from the network drive.  All the songs show and download but wont play.

**Comment by vicwomg** [comment] 2020-07-17 21:42
Could be an omxplayer limitation with network mounts. Can you play it from the command line like this? 

```omxplayer <path_to_file>```

**Comment by Rwestrem** [comment] 2020-07-17 23:04
It played via omxplayer

**Comment by vicwomg** [comment] 2020-07-18 00:54
Hmm, running out of ideas. If you can, run the pikaraoke with the debug logging option: 
`python app.py --log-level 10`

Try to play a file and post the log output

**Comment by Rwestrem** [comment] 2020-07-18 19:59
I got it working.  I just put a sleep 30s then mount -a then sleep 5s then start pikaraoke with the -d and my shared drive and all works well.  I assume it's just things starting out of order is all that was the issue.  Pretty hacky way of doing it in the rc.local but it works and I'm happy.  Thank you for pushing me in the right direction.

**Comment by vicwomg** [comment] 2020-07-18 22:11
thanks for the update. Sounds like it was a synchronization issue with network mounting + autostart pikaraoke on startup, not a bug in pikaraoke itself. Closing ticket.

**Closed by vicwomg** 2020-07-18 22:11 UTC
